name       : perl-goocanvas2
version    : 0.06
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PERLMAX/GooCanvas2-0.06.tar.gz : e24c87873e19063dd4d5e2c709caacf8c0ae8881044395bb865dc2b4fdd63b50
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : GooCanvas2 - Perl binding for GooCanvas2 widget using Glib::Object::Introspection
description: |
    GooCanvas2 is a new canvas widget for use with Gtk3 that uses the Cairo 2d library for drawing. This is a simple and basic implementation of this wonderful Canvas widget.
builddeps  :
    - pkgconfig(goocanvas-3.0)
    - perl-gtk3
rundeps    :
    - goocanvas
    - perl-gtk3
setup      : |
    sed -i "s/version => '2.0'/version => '3.0'/" lib/GooCanvas2.pm
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
